
package Vista;

import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;//libreria para usar la clase ImageIcon
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;//libreria para usar Jlabel
import javax.swing.JOptionPane;
import Modelo.Archivos;
import Modelo.RepMusica;
import Modelo.RepVideo;
import javax.swing.table.DefaultTableModel; // importación para el modelo de la tabla
    

public final class PaginaPrincipal extends javax.swing.JFrame {
    
    
    
        // Configurar el modelo de la tabla1
        DefaultTableModel modeloT = new DefaultTableModel(
            new Object[]{"Nombre", "Extensión", "Artista", "Álbum", "Género", "Duración Seg", "Año", "Ruta", "Tamaño (MB)"}, 
            0
        );
        
        // Configurar el modelo de la tableVideo
        DefaultTableModel modeloVideo = new DefaultTableModel(
            new Object[]{"Nombre", "Extensión", "Duración Seg", "Ruta", "Tamaño (MB)"}, 
            0
        );
        
        File[] archivoSeleccionado;// declaración de una variable global para poder utlizarla en otros metodos del JFrame
        private RepMusica cancion;
        
    public PaginaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        cancion = new RepMusica(""); // Inicializar con una ruta vacía
        
        jTable1.setModel(modeloT);
        
        tableVideos.setModel(modeloVideo);
        
        txtPrueba.setVisible(false);
        txtPruebaVid.setVisible(false);
         //Imagenes de botones
         btnReproducir.setIcon(setIcono("/Imagenes/video.png/",btnReproducir));
         btnCrearPlaylist.setIcon(setIcono("/Imagenes/musica.png/",btnCrearPlaylist));
         btnEliminarCancion.setIcon(setIcono("/Imagenes/eliminar1.png/",btnEliminarCancion));
         btnDetenerCancion.setIcon(setIcono("/Imagenes/stop-button.png/",btnDetenerCancion));
         
         //Cambio de tamaño del boton
         btnReproducir.setPressedIcon(setIconoPresionado("/Imagenes/video.png/", btnReproducir,1,1));
         btnCrearPlaylist.setPressedIcon(setIconoPresionado("/Imagenes/musica.png/",btnCrearPlaylist,1,1));
         btnEliminarCancion.setPressedIcon(setIconoPresionado("/Imagenes/eliminar.png/",btnEliminarCancion,1,1));
         btnDetenerCancion.setPressedIcon(setIconoPresionado("/Imagenes/stop-button.png/",btnDetenerCancion,1,1));
         
         
         //Imagenes de labels
         SetImageLabel(lblCarpeta,"/Imagenes/carpeta1.png/");
         SetImageLabel(lblAgregarRuta,"/Imagenes/anadir1.png/");
         SetImageLabel(lblMusica,"/Imagenes/multimedia1.png/");
         SetImageLabel(lblImagen,"/Imagenes/galeria-de-imagenes1.png/");
         SetImageLabel(lblDuplicados,"/Imagenes/duplicar1.png/");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCarpeta = new javax.swing.JLabel();
        btnAgregarRuta = new javax.swing.JButton();
        btnMusica = new javax.swing.JButton();
        btnVideo = new javax.swing.JButton();
        btnDuplicados = new javax.swing.JButton();
        lblAgregarRuta = new javax.swing.JLabel();
        lblMusica = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblDuplicados = new javax.swing.JLabel();
        txtPrueba = new javax.swing.JTextField();
        txtPruebaVid = new javax.swing.JTextField();
        btnImagenes = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVideos = new javax.swing.JTable();
        btnReproducirVid = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnReproducir = new javax.swing.JButton();
        btnEliminarCancion = new javax.swing.JButton();
        btnCrearPlaylist = new javax.swing.JButton();
        txtCantidadArchivosMusica = new javax.swing.JTextField();
        txtDuplicadosMusica = new javax.swing.JTextField();
        txtPesoTotalMusica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTamañoDuplicadosMusica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnDetenerCancion = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        JpanelVid = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 227, 207));

        btnAgregarRuta.setBackground(new java.awt.Color(187, 34, 51));
        btnAgregarRuta.setFont(new java.awt.Font("Geomanist Black", 1, 12)); // NOI18N
        btnAgregarRuta.setForeground(new java.awt.Color(250, 227, 207));
        btnAgregarRuta.setText("Agregar Ruta");
        btnAgregarRuta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAgregarRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRutaActionPerformed(evt);
            }
        });

        btnMusica.setBackground(new java.awt.Color(187, 34, 51));
        btnMusica.setFont(new java.awt.Font("Geomanist Black", 1, 12)); // NOI18N
        btnMusica.setForeground(new java.awt.Color(250, 227, 207));
        btnMusica.setText("Música ");
        btnMusica.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });

        btnVideo.setBackground(new java.awt.Color(187, 34, 51));
        btnVideo.setFont(new java.awt.Font("Geomanist Black", 1, 12)); // NOI18N
        btnVideo.setForeground(new java.awt.Color(250, 227, 207));
        btnVideo.setText("Video");
        btnVideo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVideo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVideoActionPerformed(evt);
            }
        });

        btnDuplicados.setBackground(new java.awt.Color(187, 34, 51));
        btnDuplicados.setFont(new java.awt.Font("Geomanist Black", 1, 12)); // NOI18N
        btnDuplicados.setForeground(new java.awt.Color(250, 227, 207));
        btnDuplicados.setText("Mostrar Duplicados");
        btnDuplicados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDuplicados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnImagenes.setBackground(new java.awt.Color(187, 34, 51));
        btnImagenes.setFont(new java.awt.Font("Geomanist Black", 1, 12)); // NOI18N
        btnImagenes.setForeground(new java.awt.Color(250, 227, 207));
        btnImagenes.setText("Imagenes");
        btnImagenes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnImagenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(btnVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPruebaVid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAgregarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDuplicados, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDuplicados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnImagenes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgregarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDuplicados, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(txtPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnDuplicados, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPruebaVid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 230, 730));

        tableVideos.setFont(new java.awt.Font("Geomanist Book", 0, 12)); // NOI18N
        tableVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Extensión", "Duración", "Ruta", "Tamaño"
            }
        ));
        tableVideos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVideosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableVideos);

        btnReproducirVid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReproducirVid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReproducirVidMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnReproducirVid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnReproducirVid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setToolTipText("");
        jPanel4.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Geomanist Book", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Extensión", "Artista", "Albúm", "Género", "Duración", "Año", "Ruta", "Tamaño"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Nombre");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Extensión");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Artista");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Albúm");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Género");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Duración");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Año");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("Ruta");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("Tamaño");
        }

        btnReproducir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReproducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReproducirMouseClicked(evt);
            }
        });

        btnEliminarCancion.setToolTipText("");
        btnEliminarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCancionActionPerformed(evt);
            }
        });

        btnCrearPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtCantidadArchivosMusica.setEditable(false);

        txtDuplicadosMusica.setEditable(false);

        txtPesoTotalMusica.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Geomanist Book", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad de archivos");

        jLabel3.setFont(new java.awt.Font("Geomanist Book", 1, 14)); // NOI18N
        jLabel3.setText("Archivos Duplicados");

        jLabel4.setFont(new java.awt.Font("Geomanist Book", 1, 14)); // NOI18N
        jLabel4.setText("Tamaño Total de Archivos");

        txtTamañoDuplicadosMusica.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Geomanist Book", 1, 14)); // NOI18N
        jLabel5.setText("Tamaño Total Duplicados");

        btnDetenerCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerCancionActionPerformed(evt);
            }
        });

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Geomanist Bold", 0, 14)); // NOI18N
        jLabel6.setText("Ruta:");

        txtRuta.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnCrearPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnDetenerCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnEliminarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTamañoDuplicadosMusica, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtCantidadArchivosMusica)
                            .addComponent(txtDuplicadosMusica)
                            .addComponent(txtPesoTotalMusica))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadArchivosMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDuplicadosMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTamañoDuplicadosMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesoTotalMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetenerCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        javax.swing.GroupLayout JpanelVidLayout = new javax.swing.GroupLayout(JpanelVid);
        JpanelVid.setLayout(JpanelVidLayout);
        JpanelVidLayout.setHorizontalGroup(
            JpanelVidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        JpanelVidLayout.setVerticalGroup(
            JpanelVidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelVid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JpanelVid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 880, 630));

        jPanel1.setBackground(new java.awt.Color(187, 34, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Geomanist Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 227, 207));
        jLabel2.setText("GESTOR PRO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 0, 310, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 880, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //funcionalidad de los botones
    private void btnAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRutaActionPerformed
       /* Ruta ruta = new Ruta();//Creamos un objeto de tipo Ruta (ventana donde esta el selector de archivos)
        ruta.setDefaultCloseOperation(PaginaPrincipal.DISPOSE_ON_CLOSE);//Esto permite que, al cerrar la ventana secundaria, no se cierre la ventana principal
        ruta.setVisible(true);//Hace que la ventana sea visible*/
       
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.setMultiSelectionEnabled(true); // Permitir seleccionar múltiples archivos
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int respuesta = jFileChooser1.showOpenDialog(null);
        
        if(respuesta == JFileChooser.APPROVE_OPTION){
            
            
            File nombre = jFileChooser1.getSelectedFile();
            archivoSeleccionado = jFileChooser1.getSelectedFiles();
            
            
            String [] extensiones = {".mp3", ".wma", ".flv"}; //Declaración de extensiones para música
            modeloT.setRowCount(0); // Limpiar datos anteriores
            
            String [] extensionesVid = {".mp4"}; //Declaración de extensiones para videos
            modeloVideo.setRowCount(0); // Limpiar datos anteriores
            
            //objeto para la musica 
            Archivos archivoMusica = new Archivos(archivoSeleccionado);
            double tamanioByte = archivoMusica.tamanioArchivos(archivoSeleccionado, extensiones);
            double tamanioGB = tamanioByte / (1024 * 1024 * 1024);//Convierte el tamaño a GB
               
            long cantidad = 0;
            double tamanioByte1 = 0;
            double tamanioGB1 = 0;
            long cantidadDup = 0;
            
            //objeto para video
            RepVideo archivoVideo = new RepVideo(archivoSeleccionado);
            double tamanioByteVid = archivoMusica.tamanioArchivos(archivoSeleccionado, extensiones);
            double tamanioGBVid = tamanioByte / (1024 * 1024 * 1024);//Convierte el tamaño a GB
               
            long cantidadVid = 0;
            double tamanioByteVid1 = 0;
            double tamanioGBVid1 = 0;
            long cantidadDupVid = 0;
               
            //bucle para entrar a los archivos
            for(File archivo : archivoSeleccionado){
                //declaración para musica
                cantidad = archivoMusica.contarArchivo(archivo, extensiones);
                tamanioByte1 = archivoMusica.tamanioArchivosDuplicados(archivo, extensiones);
                cantidadDup = archivoMusica.archivosDuplicados(archivo, extensiones);
                archivoMusica.mostrarArchivosMusica(archivo, modeloT, extensiones);//Meter los datos en bucle al JTable
                
                //declaración para video
                cantidadVid = archivoMusica.contarArchivo(archivo, extensiones);
                tamanioByteVid1 = archivoMusica.tamanioArchivosDuplicados(archivo, extensiones);
                cantidadDupVid = archivoMusica.archivosDuplicados(archivo, extensiones);
                archivoVideo.mostrarArchivoVideo(archivo, modeloVideo, extensionesVid);
            }
            tamanioGB1 = tamanioByte1 / (1024 * 1024 * 1024);
            tamanioGBVid1 = tamanioByte1 / (1024 * 1024 * 1024);
            
            if(nombre == null || nombre.getName().equals("")){
                JOptionPane.showMessageDialog(null, "Error al abrir el archivo");
            }
            else{
                txtRuta.setText(nombre.getAbsolutePath());
                txtPesoTotalMusica.setText(String.format("%.6f GB" , tamanioGB));
                txtCantidadArchivosMusica.setText(String.valueOf(cantidad));
                txtDuplicadosMusica.setText(String.valueOf(cantidadDup));
                txtTamañoDuplicadosMusica.setText(String.format("%.6f GB" , tamanioGB1));
                
            }
        }
    }//GEN-LAST:event_btnAgregarRutaActionPerformed

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
       jTabbedPane1.setSelectedIndex(1);//No manda a la pestaña 2 del tabbedPane
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.rowAtPoint(evt.getPoint());
        txtPrueba.setText(jTable1.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCancionActionPerformed
        if(!"".equals(txtPrueba.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null,"Esta seguro de que quiere eliminar esta canción?");
            if(pregunta == 0){
                Archivos archivoMusica = new Archivos(archivoSeleccionado);
                archivoMusica.eliminarCanción(txtPrueba);
                limpiarTable();
                cargarDatosTablaMusica();  
                actualizarCamposMusica();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna canción");
        }
    }//GEN-LAST:event_btnEliminarCancionActionPerformed

    private void btnReproducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReproducirMouseClicked
        String ruta = txtPrueba.getText();
        System.out.println("Ruta del archivo: " + ruta);
        cancion.pararAudio();
        cancion = new RepMusica(ruta);
        cancion.reproducirAudio();
        
    }//GEN-LAST:event_btnReproducirMouseClicked

    private void btnDetenerCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerCancionActionPerformed
        cancion.pausarAudio();
    }//GEN-LAST:event_btnDetenerCancionActionPerformed

    private void tableVideosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVideosMouseClicked
        int fila = tableVideos.rowAtPoint(evt.getPoint());
        txtPruebaVid.setText(tableVideos.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tableVideosMouseClicked

    private void btnReproducirVidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReproducirVidMouseClicked

    }//GEN-LAST:event_btnReproducirVidMouseClicked

    private void btnVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVideoActionPerformed
        jTabbedPane1.setSelectedIndex(0);//No manda a la pestaña 1 del tabbedPane
    }//GEN-LAST:event_btnVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }
    
    //Método para agregar imagenes a los labels
    private void SetImageLabel(JLabel labelName, String root){
        //Se utiliza getClass().getResource si está dentro de la misma carpeta raiz
        ImageIcon image = new ImageIcon(getClass().getResource(root));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
    }
    
    //Métodos para agregarle Imagenes a los botones
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth()-5;
        int alto = boton.getHeight()-5;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
        return icono;
    }
    
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int alto){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int anchura = boton.getWidth() - ancho;
        int altura = boton.getHeight()- alto;
         
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(anchura, altura, Image.SCALE_SMOOTH));
        
        return icono;
    }
    
    public void limpiarTable(){
        for(int i = 0; i < modeloT.getRowCount(); i++){
            modeloT.removeRow(i);
            i -= 1;
        }
    }
    
    public void cargarDatosTablaMusica(){
        modeloT.setRowCount(0); // Limpiar la tabla
        File directorio = new File(txtRuta.getText());
        String[] extensiones = {".mp3", ".wma", ".flv"}; // Definimos las extensiones que queremos mostrar
        Archivos archivoMusica = new Archivos(archivoSeleccionado);
        for(File archivo : archivoSeleccionado){
         archivoMusica.mostrarArchivosMusica(directorio, modeloT, extensiones); // Llamamos al método existente para llenar la tabla
        }
    }
    
    public void actualizarCamposMusica(){
        
        String [] extensiones = {".mp3", ".wma", ".flv"}; //Declaración de extensiones para música
        Archivos archivoMusica = new Archivos(archivoSeleccionado);
            double tamanioByte = archivoMusica.tamanioArchivos(archivoSeleccionado, extensiones);
            double tamanioGB = tamanioByte / (1024 * 1024 * 1024);//Convierte el tamaño a GB
               
            long cantidad = 0;
            double tamanioByte1 = 0;
            double tamanioGB1 = 0;
            long cantidadDup = 0;
               
            for(File archivo : archivoSeleccionado){
                cantidad = archivoMusica.contarArchivo(archivo, extensiones);
                tamanioByte1 = archivoMusica.tamanioArchivosDuplicados(archivo, extensiones);
                cantidadDup = archivoMusica.archivosDuplicados(archivo, extensiones);
                archivoMusica.mostrarArchivosMusica(archivo, modeloT, extensiones);//Meter los datos en bucle al JTable
            }
            txtPesoTotalMusica.setText(String.format("%.6f GB" , tamanioGB));
            txtCantidadArchivosMusica.setText(String.valueOf(cantidad));
            txtDuplicadosMusica.setText(String.valueOf(cantidadDup));
            txtTamañoDuplicadosMusica.setText(String.format("%.6f GB" , tamanioGB1));
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelVid;
    private javax.swing.JButton btnAgregarRuta;
    private javax.swing.JButton btnCrearPlaylist;
    private javax.swing.JButton btnDetenerCancion;
    private javax.swing.JButton btnDuplicados;
    private javax.swing.JButton btnEliminarCancion;
    private javax.swing.JButton btnImagenes;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnReproducir;
    private javax.swing.JButton btnReproducirVid;
    private javax.swing.JButton btnVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAgregarRuta;
    private javax.swing.JLabel lblCarpeta;
    private javax.swing.JLabel lblDuplicados;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JTable tableVideos;
    private javax.swing.JTextField txtCantidadArchivosMusica;
    private javax.swing.JTextField txtDuplicadosMusica;
    private javax.swing.JTextField txtPesoTotalMusica;
    private javax.swing.JTextField txtPrueba;
    private javax.swing.JTextField txtPruebaVid;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtTamañoDuplicadosMusica;
    // End of variables declaration//GEN-END:variables


